"""
Django settings for drchrono_compiler project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5mgtfxem*f$14rqwq$reowcj-72cmr%ufiysgq9e_l)xf8cr=3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://drchrono-pdf-compiler.onrender.com/', 'drchrono-pdf-compiler.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://drchrono-pdf-compiler.onrender.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'verify',
    'appts',
    'core',
    'pdf',
    'search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drchrono_compiler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drchrono_compiler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        # Replace this value with your local database's connection string.
        default='postgresql://drchrono_postgressql_user:Irp4Sat7DEWGpeYmcjxQmRc97L5BpAFy@dpg-d5panj14tr6s73antdfg-a/drchrono_postgressql',
        conn_max_age=600
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

CSRF_FAILURE_VIEW = 'verify.views.csrf_failure'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DRCHRONO_CLIENT_ID = "K1Ncm5IMr7AEngYZfOexxbKYNmX2vBMAO4MuxI7g"
DRCHRONO_CLIENT_SECRET = '6EjgA3Wp0cXeNmmY6jA2yKGIHRMQDMV0eEIhQbHI96dJCNDMUVpaSFEQQOLo0axmfRPY5nfGGiivoC4cT1K1VavF3q8B6w190uKulgyOTmSKom9XcHwbcvSezpFJcMPp'
DRCHRONO_REDIRECT_URI = "http://127.0.0.1:8000/oauth/callback"
DRCHRONO_AUTH_URL = 'https://app.drchrono.com/o/authorize/'
DRCHRONO_TOKEN_URL = 'https://app.drchrono.com/o/token/'
DRCHRONO_SCOPES = 'clinical:read billing:read patients:read patients:summary:read calendar:read user:read'
